Add a quote-of-the-day feature
vitorpio/pybible-cli pull request #1
Opened 2020-03-02 03:56 UTC by tonybaloney

e.g.

```
$ pybible --qotd
"For which things' sake the wrath of God cometh on the children of disobedience:" - Colossians 3:6 (King James Bible)
```

2020-03-02 11:25 UTC, vitorpio requested changes
Simple changes

2020-03-02 11:25 UTC, vitorpio commented on pybible/__main__.py
> +    reference_group.add_argument("--qotd", help="Quote a single, random verse",
two argument options:
"-qotd"
"--quote_of_the_day"

2020-03-02 11:25 UTC, vitorpio commented on pybible/__main__.py
> +        return f"\"{verse.text}\" - {book.title} {chapter.number}:{verse.number} ({bible.name})"
replace with:
`references = [Reference(verse.text, book.title, chapter.number, verse.number)]`
too keep the new parameter the same as the others.

2020-03-02 11:25 UTC, vitorpio commented on README.md
> +    $ pybible --motd
Replace with --qotd

2020-03-03 22:23 UTC, tonybaloney commented
@vitorpio made the changes to your request

2020-03-03 22:51 UTC, merged